<a href="https://colab.research.google.com/github/sathyaithazh555-creator/CODING-CHALLENGE-DAY-4/blob/main/Day_1_Numby_arrays_and_operationsd1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#### Create 1D,2D,3D arrays
array1d=np.array([10,20,30,40])
array2d=np.array([[1,2,3],[4,5,6]])
array3d=np.array([[[1,2],[3,4],[5,6]]])
print("1D Array:",array1d)
print("2D Array:",array2d)
print("3D Array:",array3d)
##### Arithmetic operations
print("\nArithmetic operations")
print("Addition:",array1d +5)
print("subtraction:",array1d -2)
print("Multiplication:",array1d *4)
print("Division:",array1d / 3)
#### Statistical function
print("\nStatistical function")
print("Mean:",np.mean(array1d))
print("Sum:",np.sum(array1d))
print("Standard deviation:",np.std(array1d))
#### Reshape,arange,linspace
reshaped_array = np.arange(20).reshape(4,5) # Corrected np.arrange and chained reshape
print("\nReshape using arange:\n",reshaped_array)
line_array =np.linspace(0,1,3) # Corrected np.linespace
print("linspace(0 to 1):",line_array)
### Index of max,min values
print("\nmax value index:",np.argmax(array1d))
print("\nmin value index:",np.argmin(array1d))

1D Array: [10 20 30 40]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]
  [5 6]]]

Arithmetic operations
Addition: [15 25 35 45]
subtraction: [ 8 18 28 38]
Multiplication: [ 40  80 120 160]
Division: [ 3.33333333  6.66666667 10.         13.33333333]

Statistical function
Mean: 25.0
Sum: 100
Standard deviation: 11.180339887498949

Reshape using arange:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
linspace(0 to 1): [0.  0.5 1. ]

max value index: 3

min value index: 0
